/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package View;

import Process.User;
import java.beans.PropertyVetoException;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author mSoSm
 */
public class frmMain extends javax.swing.JFrame {

    public User us;
    
    
    public frmMain() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null); // display center
        hideAllButtons();
    }

    public void hideAllButtons() {
        btnMenuMn.setVisible(false);
        btnLogOut.setVisible(false);
        btnSignIn.setVisible(true);
        btnSignUp.setVisible(true);
        btnEmployees.setVisible(false);
        btnOrder.setVisible(false);
        btnMenu.setVisible(false);
    }
    
     public JDesktopPane getMyDesktop() {
    return myDesktop;
}

    
    public void receiveData(User data) {
        System.out.println("username: " + data.username);
        System.out.println("role: " + data.role);
        us = data;
        btnSignIn.setVisible(false);
        btnSignUp.setVisible(false);
        btnFogot.setVisible(false);
        btnLogOut.setVisible(true);
        btnOrder.setVisible(true);
        btnMenu.setVisible(true);
        switch (data.role) {
            case "Manager" -> {
                btnMenuMn.setVisible(true);
                
                btnEmployees.setVisible(true);
            }
            case "Chef" -> {
                btnMenuMn.setVisible(true);
            }
            case "Server" -> {
                btnMenuMn.setVisible(true);
                btnLogOut.setVisible(true);               
            }
            case "Customer" -> {
                btnMenuMn.setVisible(true);
                // Các hành động khác cho Customer
            }
            default -> {
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        panel1 = new java.awt.Panel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        myDesktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JToggleButton();
        btnSignUp = new javax.swing.JToggleButton();
        btnLogOut = new javax.swing.JButton();
        btnFogot = new javax.swing.JButton();
        btnMenuMn = new javax.swing.JButton();
        btnEmployees = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnTablesMn = new javax.swing.JButton();
        btnTables = new javax.swing.JButton();
        btnIngre = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        panel1.setLayout(new java.awt.CardLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        myDesktop.setBackground(new java.awt.Color(0, 153, 153));
        myDesktop.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);
        myDesktop.setPreferredSize(new java.awt.Dimension(1069, 768));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESTAURANT MANAGEMENT SYSTEM");

        btnSignIn.setText("SIGN IN");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        btnSignUp.setText("SIGN UP");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        btnLogOut.setText("Logout");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnFogot.setText("Fogot Password");

        btnMenuMn.setText("Menu Manager");
        btnMenuMn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMnActionPerformed(evt);
            }
        });

        btnEmployees.setText("Employees Manager");
        btnEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeesActionPerformed(evt);
            }
        });

        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnTablesMn.setText("Tables Manager");
        btnTablesMn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablesMnActionPerformed(evt);
            }
        });

        btnTables.setText("Tables");
        btnTables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablesActionPerformed(evt);
            }
        });

        btnIngre.setText("Ingredient");
        btnIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngreActionPerformed(evt);
            }
        });

        myDesktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        myDesktop.setLayer(btnSignIn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        myDesktop.setLayer(btnSignUp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        myDesktop.setLayer(btnLogOut, javax.swing.JLayeredPane.DEFAULT_LAYER);
        myDesktop.setLayer(btnFogot, javax.swing.JLayeredPane.DEFAULT_LAYER);
        myDesktop.setLayer(btnMenuMn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        myDesktop.setLayer(btnEmployees, javax.swing.JLayeredPane.DEFAULT_LAYER);
        myDesktop.setLayer(btnOrder, javax.swing.JLayeredPane.DEFAULT_LAYER);
        myDesktop.setLayer(btnMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        myDesktop.setLayer(btnTablesMn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        myDesktop.setLayer(btnTables, javax.swing.JLayeredPane.DEFAULT_LAYER);
        myDesktop.setLayer(btnIngre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout myDesktopLayout = new javax.swing.GroupLayout(myDesktop);
        myDesktop.setLayout(myDesktopLayout);
        myDesktopLayout.setHorizontalGroup(
            myDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myDesktopLayout.createSequentialGroup()
                .addComponent(btnEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(191, 191, 191))
            .addGroup(myDesktopLayout.createSequentialGroup()
                .addGroup(myDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnIngre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTables, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTablesMn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuMn, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(myDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myDesktopLayout.createSequentialGroup()
                        .addGroup(myDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(myDesktopLayout.createSequentialGroup()
                                .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnFogot, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(220, 220, 220))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myDesktopLayout.createSequentialGroup()
                        .addComponent(btnLogOut)
                        .addGap(80, 80, 80))))
        );
        myDesktopLayout.setVerticalGroup(
            myDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myDesktopLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(145, 145, 145)
                .addGroup(myDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnFogot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(myDesktopLayout.createSequentialGroup()
                .addComponent(btnEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuMn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnTablesMn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTables, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnIngre, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(myDesktop, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(myDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jDesktopPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeesActionPerformed
        // TODO add your handling code here:
        frmEmployees frm = new frmEmployees();
        myDesktop.add(frm);
        frm.setVisible(true);

    }//GEN-LAST:event_btnEmployeesActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        for (JInternalFrame frame : myDesktop.getAllFrames()) {
        frame.dispose(); // Hoặc frame.setVisible(false);
    }
        hideAllButtons();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnMenuMnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMnActionPerformed
        frmMenuManager frm =new frmMenuManager();
        frm.receivedata(us);
        myDesktop.add(frm);
        frm.setVisible(true);

    }//GEN-LAST:event_btnMenuMnActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        frmSignUp frm = new frmSignUp();
        myDesktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        frmLogin frm =new frmLogin(this);
        myDesktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        frmOrder frm = null;
        for (JInternalFrame frame : myDesktop.getAllFrames()) {
            if (frame instanceof frmOrder) {
                frm = (frmOrder) frame;
                break;
            }
        }
        // Nếu frmOrder đã được mở, chỉ cần kích hoạt nó
        if (frm != null) {
            try {
                if (frm.isIcon()) { // Kiểm tra nếu nó đang bị thu nhỏ
                    frm.setIcon(false); // Mở lại frmOrder
                }
                frm.toFront(); // Đưa frmOrder lên trên
                frm.requestFocus(); // Yêu cầu focus cho frmOrder
            } catch (PropertyVetoException e) {
                JOptionPane.showMessageDialog(null, "Lỗi khi mở lại cửa sổ đơn hàng: " + e.getMessage());
                e.printStackTrace();
            }
        } else {
            // Nếu frmOrder chưa được mở, tạo một thể hiện mới và hiển thị
            frm = new frmOrder();
            frm.receivedata(us);
            myDesktop.add(frm);
            frm.setVisible(true);
        }
    }//GEN-LAST:event_btnOrderActionPerformed

    
    
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        frmMenu frm = new frmMenu();
        frm.hideTable();
        myDesktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnTablesMnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablesMnActionPerformed
        // TODO add your handling code here:
        frmTableManager frm =new frmTableManager();
        myDesktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_btnTablesMnActionPerformed

    private void btnTablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablesActionPerformed
        // TODO add your handling code here:
        frmTables frm =new frmTables(us);
        myDesktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_btnTablesActionPerformed

    private void btnIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngreActionPerformed
        // TODO add your handling code here:
        frmIngredient frm = new frmIngredient();
        myDesktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_btnIngreActionPerformed
    
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployees;
    private javax.swing.JButton btnFogot;
    private javax.swing.JButton btnIngre;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMenuMn;
    private javax.swing.JButton btnOrder;
    private javax.swing.JToggleButton btnSignIn;
    private javax.swing.JToggleButton btnSignUp;
    private javax.swing.JButton btnTables;
    private javax.swing.JButton btnTablesMn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JDesktopPane myDesktop;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables

}
